import type { TOperation } from '../types';
import { ScenarioTypeAdapter } from './adapter';

type TemplateContract = {
  ofAllEndpoints(operations: TOperation[]): string;
};

class ScenarioTypeTemplate implements TemplateContract {
  ofAllEndpoints(operations: TOperation[]): string {
    const adapter = new ScenarioTypeAdapter(operations);

    const apiEndpointsType = `export type TApiEndpoints = {
${adapter.apiEndpointsType};
};`;

    const apiPathsType = 'export type TApiPaths = keyof TApiEndpoints;';

    const apiMethodsType = 'export type TApiMethods<T extends TApiPaths> = TApiEndpoints[T];';

    const statusCodesType = `export type TApiStatusCodes = {
${adapter.statusCodesType}
};`;

    const scenarioConfigType = `export type TScenarioConfig = {
  [scenarioId: string]: {
    description: string;
  } & ({
    type: 'custom-status';
    api: {
      [K in TApiPaths]?: {
        [M in TApiMethods<K>]?: {
          status: TApiStatusCodes[K][M];
          allowCustomStatus?: boolean;
        } | {
          status: number;
          allowCustomStatus: true;
        };
      };
    };
  } | {
    type: 'api-recorder';
    demoData: unknown;
  });
};`;

    return `/**
 * This file is AUTO GENERATED by [msw-auto-mock](https://github.com/dhlab-org/msw-auto-mock)
 * Feel free to commit/edit it as you need.
 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

${apiEndpointsType}

${apiPathsType}

${apiMethodsType}

${statusCodesType}

${scenarioConfigType}
`;
  }
}

export { ScenarioTypeTemplate, type TemplateContract as ScenarioTypeTemplateContract };
